// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Nozomi.net
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for ComponentService.
    /// </summary>
    public static partial class ComponentExtensions
    {
            /// <summary>
            /// Obtain all components you have created.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='requestGuid'>
            /// The unique identifier of the request that contains this component.
            /// </param>
            /// <param name='index'>
            /// The 'page' of the list of results in 100s
            /// </param>
            public static object All(this IComponentService operations, string requestGuid, int? index = 0)
            {
                return operations.AllAsync(requestGuid, index).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Obtain all components you have created.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.-
            /// </param>
            /// <param name='requestGuid'>
            /// The unique identifier of the request that contains this component.
            /// </param>
            /// <param name='index'>
            /// The 'page' of the list of results in 100s
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> AllAsync(this IComponentService operations, string requestGuid, 
                int? index = 0, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations
                    .All(requestGuid, index, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Create a component.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// The supposed properties/parameters of the component.
            /// </param>
            public static string Create(this IComponentService operations, 
                CreateComponentInputModel body = default(CreateComponentInputModel))
            {
                return CreateAsync(operations, body).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Create a component.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// The supposed properties/parameters of the component.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<string> CreateAsync(this IComponentService operations, 
                CreateComponentInputModel body = default(CreateComponentInputModel), 
                CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.CreateAsync(body, cancellationToken)
                    .ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Delete a component.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='guid'>
            /// The unique identifier of the component to delete.
            /// </param>
            public static string Delete(this IComponentService operations, string guid = default(string))
            {
                return DeleteAsync(operations, guid).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Delete a component.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='guid'>
            /// The unique identifier of the component to delete.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<string> DeleteAsync(this IComponentService operations, 
                string guid = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.DeleteAsync(guid, cancellationToken)
                    .ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Obtain the component and its historical values.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='guid'>
            /// The unique identifier of the component.
            /// </param>
            /// <param name='index'>
            /// The 'page' of the list of historical values in 100s
            /// </param>
            public static object Get(this IComponentService operations, string guid, int? index = 0)
            {
                return GetAsync(operations, guid, index).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Obtain the component and its historical values.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='guid'>
            /// The unique identifier of the component.
            /// </param>
            /// <param name='index'>
            /// The 'page' of the list of historical values in 100s
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetAsync(this IComponentService operations, string guid, int? index = 0, 
                CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetAsync(guid, index, cancellationToken)
                    .ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Update a component.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// The supposed properties/parameters of the component.
            /// </param>
            public static string Update(this IComponentService operations, 
                UpdateComponentInputModel body = default(UpdateComponentInputModel))
            {
                return UpdateAsync(operations, body).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Update a component.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// The supposed properties/parameters of the component.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<string> UpdateAsync(this IComponentService operations, 
                UpdateComponentInputModel body = default(UpdateComponentInputModel), 
                CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.UpdateAsync(body, cancellationToken)
                    .ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
