// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using System.Threading;
using System.Threading.Tasks;

namespace Nozomi.net.Services.Extensions
{
    /// <summary>
    /// Extension methods for ComputeValue.
    /// </summary>
    public static partial class ComputeValueExtensions
    {
            /// <summary>
            /// Obtain all compute value generated.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='index'>
            /// The 'page' of the list of results in x
            /// </param>
            /// <param name='computeGuid'>
            /// The compute guid relating to the values in question, optional.
            /// </param>
            public static object GET(this IComputeValue operations, int index, string computeGuid = default(string))
            {
                return operations.GETAsync(index, computeGuid).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Obtain all compute value generated.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='index'>
            /// The 'page' of the list of results in x
            /// </param>
            /// <param name='computeGuid'>
            /// The compute guid relating to the values in question, optional.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GETAsync(this IComputeValue operations, int index, string computeGuid = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GETWithHttpMessagesAsync(index, computeGuid, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Obtain the compute value specified.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='guid'>
            /// The guid of the compute value in question.
            /// </param>
            public static object GET1(this IComputeValue operations, string guid)
            {
                return operations.GET1Async(guid).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Obtain the compute value specified.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='guid'>
            /// The guid of the compute value in question.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GET1Async(this IComputeValue operations, string guid, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GET1WithHttpMessagesAsync(guid, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Obtain the last compute value of the compute in question.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='computeGuid'>
            /// The compute in question.
            /// </param>
            public static object GET2(this IComputeValue operations, string computeGuid)
            {
                return operations.GET2Async(computeGuid).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Obtain the last compute value of the compute in question.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='computeGuid'>
            /// The compute in question.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GET2Async(this IComputeValue operations, string computeGuid, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GET2WithHttpMessagesAsync(computeGuid, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
