// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Nozomi.net
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for RequestProperty.
    /// </summary>
    public static partial class RequestPropertyExtensions
    {
            /// <summary>
            /// Obtain all request properties you have created/own.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='index'>
            /// The 'page' of the list of results in 100s.
            /// </param>
            public static object GET(this IRequestProperty operations, int? index = 0)
            {
                return operations.GETAsync(index).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Obtain all request properties you have created/own.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='index'>
            /// The 'page' of the list of results in 100s.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GETAsync(this IRequestProperty operations, int? index = 0, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GETWithHttpMessagesAsync(index, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Obtain all analysed components you have created, relative to that specific
            /// request.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='requestGuid'>
            /// The request guid you are referring to.
            /// </param>
            /// <param name='index'>
            /// The 'page' of the list of results in 100s.
            /// </param>
            public static object GET1(this IRequestProperty operations, string requestGuid = default(string), int? index = 0)
            {
                return operations.GET1Async(requestGuid, index).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Obtain all analysed components you have created, relative to that specific
            /// request.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='requestGuid'>
            /// The request guid you are referring to.
            /// </param>
            /// <param name='index'>
            /// The 'page' of the list of results in 100s.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GET1Async(this IRequestProperty operations, string requestGuid = default(string), int? index = 0, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GET1WithHttpMessagesAsync(requestGuid, index, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Create a request property.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// The supposed properties/parameters of the request property.
            /// </param>
            public static string POST(this IRequestProperty operations, CreateRequestPropertyInputModel body = default(CreateRequestPropertyInputModel))
            {
                return operations.POSTAsync(body).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Create a request property.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// The supposed properties/parameters of the request property.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<string> POSTAsync(this IRequestProperty operations, CreateRequestPropertyInputModel body = default(CreateRequestPropertyInputModel), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.POSTWithHttpMessagesAsync(body, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Delete a request property
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='guid'>
            /// The unique identifier of the deletion attempt.
            /// </param>
            public static string DELETE(this IRequestProperty operations, string guid)
            {
                return operations.DELETEAsync(guid).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Delete a request property
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='guid'>
            /// The unique identifier of the deletion attempt.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<string> DELETEAsync(this IRequestProperty operations, string guid, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.DELETEWithHttpMessagesAsync(guid, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Update a request property.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// The supposed properties/parameters of the request property.
            /// </param>
            public static string PUT(this IRequestProperty operations, UpdateRequestPropertyInputModel body = default(UpdateRequestPropertyInputModel))
            {
                return operations.PUTAsync(body).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Update a request property.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// The supposed properties/parameters of the request property.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<string> PUTAsync(this IRequestProperty operations, UpdateRequestPropertyInputModel body = default(UpdateRequestPropertyInputModel), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PUTWithHttpMessagesAsync(body, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
