// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Nozomi.net
{
    using Models;
    using Newtonsoft.Json;

    /// <summary>
    /// </summary>
    public partial interface INozomiAPI : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }


        /// <summary>
        /// Gets the IComponent.
        /// </summary>
        IComponent Component { get; }

        /// <summary>
        /// Gets the IComponentHistoricItem.
        /// </summary>
        IComponentHistoricItem ComponentHistoricItem { get; }

        /// <summary>
        /// Gets the IComponentType.
        /// </summary>
        IComponentType ComponentType { get; }

        /// <summary>
        /// Gets the ICompute.
        /// </summary>
        ICompute Compute { get; }

        /// <summary>
        /// Gets the IComputeExpression.
        /// </summary>
        IComputeExpression ComputeExpression { get; }

        /// <summary>
        /// Gets the IComputeValue.
        /// </summary>
        IComputeValue ComputeValue { get; }

        /// <summary>
        /// Gets the IConnect.
        /// </summary>
        IConnect Connect { get; }

        /// <summary>
        /// Gets the IItem.
        /// </summary>
        IItem Item { get; }

        /// <summary>
        /// Gets the IRequest.
        /// </summary>
        IRequest Request { get; }

        /// <summary>
        /// Gets the IRequestProperty.
        /// </summary>
        IRequestProperty RequestProperty { get; }

        /// <summary>
        /// Gets the ISubCompute.
        /// </summary>
        ISubCompute SubCompute { get; }

        /// <summary>
        /// Gets the IWebsocketCommand.
        /// </summary>
        IWebsocketCommand WebsocketCommand { get; }

        /// <summary>
        /// Gets the IWebsocketCommandProperty.
        /// </summary>
        IWebsocketCommandProperty WebsocketCommandProperty { get; }

    }
}
