// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Nozomi.net.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ComponentHistoricItemViewModel
    {
        /// <summary>
        /// Initializes a new instance of the ComponentHistoricItemViewModel
        /// class.
        /// </summary>
        public ComponentHistoricItemViewModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ComponentHistoricItemViewModel
        /// class.
        /// </summary>
        public ComponentHistoricItemViewModel(System.DateTime? timestamp = default(System.DateTime?), string value = default(string))
        {
            Timestamp = timestamp;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timestamp")]
        public System.DateTime? Timestamp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

    }
}
