// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Nozomi.net.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ComputeViewModel
    {
        /// <summary>
        /// Initializes a new instance of the ComputeViewModel class.
        /// </summary>
        public ComputeViewModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ComputeViewModel class.
        /// </summary>
        public ComputeViewModel(System.Guid? guid = default(System.Guid?), string key = default(string), string formula = default(string), int? delay = default(int?), int? failCount = default(int?), bool? isEnabled = default(bool?), IList<ComputeExpressionViewModel> expressions = default(IList<ComputeExpressionViewModel>), IList<SubComputeViewModel> childComputes = default(IList<SubComputeViewModel>), IList<SubComputeViewModel> parentComputes = default(IList<SubComputeViewModel>), IList<ComputeValueViewModel> values = default(IList<ComputeValueViewModel>))
        {
            Guid = guid;
            Key = key;
            Formula = formula;
            Delay = delay;
            FailCount = failCount;
            IsEnabled = isEnabled;
            Expressions = expressions;
            ChildComputes = childComputes;
            ParentComputes = parentComputes;
            Values = values;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "guid")]
        public System.Guid? Guid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "key")]
        public string Key { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "formula")]
        public string Formula { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "delay")]
        public int? Delay { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "failCount")]
        public int? FailCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isEnabled")]
        public bool? IsEnabled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "expressions")]
        public IList<ComputeExpressionViewModel> Expressions { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "childComputes")]
        public IList<SubComputeViewModel> ChildComputes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "parentComputes")]
        public IList<SubComputeViewModel> ParentComputes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "values")]
        public IList<ComputeValueViewModel> Values { get; set; }

    }
}
