// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Nozomi.net.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CreateComponentInputModel
    {
        /// <summary>
        /// Initializes a new instance of the CreateComponentInputModel class.
        /// </summary>
        public CreateComponentInputModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateComponentInputModel class.
        /// </summary>
        public CreateComponentInputModel(long? componentTypeId = default(long?), string identifier = default(string), string query = default(string), bool? isDenominated = default(bool?), bool? anomalyIgnorance = default(bool?), bool? storeHistoricals = default(bool?), string requestId = default(string))
        {
            ComponentTypeId = componentTypeId;
            Identifier = identifier;
            Query = query;
            IsDenominated = isDenominated;
            AnomalyIgnorance = anomalyIgnorance;
            StoreHistoricals = storeHistoricals;
            RequestId = requestId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "componentTypeId")]
        public long? ComponentTypeId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "identifier")]
        public string Identifier { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "query")]
        public string Query { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isDenominated")]
        public bool? IsDenominated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "anomalyIgnorance")]
        public bool? AnomalyIgnorance { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "storeHistoricals")]
        public bool? StoreHistoricals { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requestId")]
        public string RequestId { get; set; }

    }
}
