// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Nozomi.net.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CreateRequestInputModel
    {
        /// <summary>
        /// Initializes a new instance of the CreateRequestInputModel class.
        /// </summary>
        public CreateRequestInputModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateRequestInputModel class.
        /// </summary>
        public CreateRequestInputModel(int? requestType = default(int?), int? responseType = default(int?), string endpoint = default(string), int? delay = default(int?), long? failureDelay = default(long?), IList<CreateComponentInputModel> components = default(IList<CreateComponentInputModel>), IList<CreateRequestPropertyInputModel> properties = default(IList<CreateRequestPropertyInputModel>), IList<CreateItemRequestInputModel> items = default(IList<CreateItemRequestInputModel>), IList<CreateWebsocketCommandInputModel> websocketCommands = default(IList<CreateWebsocketCommandInputModel>))
        {
            RequestType = requestType;
            ResponseType = responseType;
            Endpoint = endpoint;
            Delay = delay;
            FailureDelay = failureDelay;
            Components = components;
            Properties = properties;
            Items = items;
            WebsocketCommands = websocketCommands;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requestType")]
        public int? RequestType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "responseType")]
        public int? ResponseType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "endpoint")]
        public string Endpoint { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "delay")]
        public int? Delay { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "failureDelay")]
        public long? FailureDelay { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "components")]
        public IList<CreateComponentInputModel> Components { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "properties")]
        public IList<CreateRequestPropertyInputModel> Properties { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IList<CreateItemRequestInputModel> Items { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "websocketCommands")]
        public IList<CreateWebsocketCommandInputModel> WebsocketCommands { get; set; }

    }
}
