// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Nozomi.net.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CreateItemSourceInputModel
    {
        /// <summary>
        /// Initializes a new instance of the CreateItemSourceInputModel class.
        /// </summary>
        public CreateItemSourceInputModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateItemSourceInputModel class.
        /// </summary>
        public CreateItemSourceInputModel(System.Guid? itemGuid = default(System.Guid?), ItemViewModel item = default(ItemViewModel), long? sourceId = default(long?), SourceViewModel source = default(SourceViewModel))
        {
            ItemGuid = itemGuid;
            Item = item;
            SourceId = sourceId;
            Source = source;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "itemGuid")]
        public System.Guid? ItemGuid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "item")]
        public ItemViewModel Item { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sourceId")]
        public long? SourceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "source")]
        public SourceViewModel Source { get; set; }

    }
}
