// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Nozomi.net.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CreateItemInputModel
    {
        /// <summary>
        /// Initializes a new instance of the CreateItemInputModel class.
        /// </summary>
        public CreateItemInputModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateItemInputModel class.
        /// </summary>
        public CreateItemInputModel(string logoPath = default(string), string abbreviation = default(string), string slug = default(string), string name = default(string), int? denominations = default(int?), string denominationName = default(string), IList<System.Guid?> typeGuids = default(IList<System.Guid?>), IList<CreateItemPropertyInputModel> properties = default(IList<CreateItemPropertyInputModel>), IList<CreateItemSourceInputModel> sources = default(IList<CreateItemSourceInputModel>), IList<CreateItemRequestInputModel> requests = default(IList<CreateItemRequestInputModel>))
        {
            LogoPath = logoPath;
            Abbreviation = abbreviation;
            Slug = slug;
            Name = name;
            Denominations = denominations;
            DenominationName = denominationName;
            TypeGuids = typeGuids;
            Properties = properties;
            Sources = sources;
            Requests = requests;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "logoPath")]
        public string LogoPath { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "abbreviation")]
        public string Abbreviation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "slug")]
        public string Slug { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "denominations")]
        public int? Denominations { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "denominationName")]
        public string DenominationName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "typeGuids")]
        public IList<System.Guid?> TypeGuids { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "properties")]
        public IList<CreateItemPropertyInputModel> Properties { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sources")]
        public IList<CreateItemSourceInputModel> Sources { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requests")]
        public IList<CreateItemRequestInputModel> Requests { get; set; }

    }
}
