// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Nozomi.net.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CreateWebsocketCommandInputModel
    {
        /// <summary>
        /// Initializes a new instance of the CreateWebsocketCommandInputModel
        /// class.
        /// </summary>
        public CreateWebsocketCommandInputModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateWebsocketCommandInputModel
        /// class.
        /// </summary>
        public CreateWebsocketCommandInputModel(int? type = default(int?), string name = default(string), long? delay = default(long?), System.Guid? requestGuid = default(System.Guid?), bool? isEnabled = default(bool?), IList<CreateWebsocketCommandPropertyInputModel> properties = default(IList<CreateWebsocketCommandPropertyInputModel>))
        {
            Type = type;
            Name = name;
            Delay = delay;
            RequestGuid = requestGuid;
            IsEnabled = isEnabled;
            Properties = properties;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public int? Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "delay")]
        public long? Delay { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requestGuid")]
        public System.Guid? RequestGuid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isEnabled")]
        public bool? IsEnabled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "properties")]
        public IList<CreateWebsocketCommandPropertyInputModel> Properties { get; set; }

    }
}
