// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Nozomi.net.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ItemSourceViewModel
    {
        /// <summary>
        /// Initializes a new instance of the ItemSourceViewModel class.
        /// </summary>
        public ItemSourceViewModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ItemSourceViewModel class.
        /// </summary>
        public ItemSourceViewModel(long? id = default(long?), System.Guid? itemGuid = default(System.Guid?), ItemViewModel item = default(ItemViewModel), long? sourceId = default(long?), System.Guid? sourceGuid = default(System.Guid?), SourceViewModel source = default(SourceViewModel))
        {
            Id = id;
            ItemGuid = itemGuid;
            Item = item;
            SourceId = sourceId;
            SourceGuid = sourceGuid;
            Source = source;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "itemGuid")]
        public System.Guid? ItemGuid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "item")]
        public ItemViewModel Item { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sourceId")]
        public long? SourceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sourceGuid")]
        public System.Guid? SourceGuid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "source")]
        public SourceViewModel Source { get; set; }

    }
}
