// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Nozomi.net.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ItemRequestViewModel
    {
        /// <summary>
        /// Initializes a new instance of the ItemRequestViewModel class.
        /// </summary>
        public ItemRequestViewModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ItemRequestViewModel class.
        /// </summary>
        public ItemRequestViewModel(System.Guid? guid = default(System.Guid?), long? requestId = default(long?), RequestViewModel request = default(RequestViewModel), System.Guid? itemGuid = default(System.Guid?), ItemViewModel item = default(ItemViewModel))
        {
            Guid = guid;
            RequestId = requestId;
            Request = request;
            ItemGuid = itemGuid;
            Item = item;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "guid")]
        public System.Guid? Guid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requestId")]
        public long? RequestId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "request")]
        public RequestViewModel Request { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "itemGuid")]
        public System.Guid? ItemGuid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "item")]
        public ItemViewModel Item { get; set; }

    }
}
