// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Nozomi.net.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ItemPropertyViewModel
    {
        /// <summary>
        /// Initializes a new instance of the ItemPropertyViewModel class.
        /// </summary>
        public ItemPropertyViewModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ItemPropertyViewModel class.
        /// </summary>
        public ItemPropertyViewModel(System.Guid? guid = default(System.Guid?), string name = default(string), string value = default(string), System.Guid? itemGuid = default(System.Guid?), ItemViewModel item = default(ItemViewModel))
        {
            Guid = guid;
            Name = name;
            Value = value;
            ItemGuid = itemGuid;
            Item = item;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "guid")]
        public System.Guid? Guid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "itemGuid")]
        public System.Guid? ItemGuid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "item")]
        public ItemViewModel Item { get; set; }

    }
}
