// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Nozomi.net.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class RequestViewModel
    {
        /// <summary>
        /// Initializes a new instance of the RequestViewModel class.
        /// </summary>
        public RequestViewModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RequestViewModel class.
        /// </summary>
        public RequestViewModel(System.Guid? guid = default(System.Guid?), int? requestType = default(int?), int? responseType = default(int?), string endpoint = default(string), int? delay = default(int?), long? failureDelay = default(long?), bool? isEnabled = default(bool?), IList<ComponentViewModel> components = default(IList<ComponentViewModel>), IList<ItemRequestViewModel> items = default(IList<ItemRequestViewModel>), IList<RequestPropertyViewModel> properties = default(IList<RequestPropertyViewModel>), IList<WebsocketCommandViewModel> websocketCommands = default(IList<WebsocketCommandViewModel>))
        {
            Guid = guid;
            RequestType = requestType;
            ResponseType = responseType;
            Endpoint = endpoint;
            Delay = delay;
            FailureDelay = failureDelay;
            IsEnabled = isEnabled;
            Components = components;
            Items = items;
            Properties = properties;
            WebsocketCommands = websocketCommands;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "guid")]
        public System.Guid? Guid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requestType")]
        public int? RequestType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "responseType")]
        public int? ResponseType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "endpoint")]
        public string Endpoint { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "delay")]
        public int? Delay { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "failureDelay")]
        public long? FailureDelay { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isEnabled")]
        public bool? IsEnabled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "components")]
        public IList<ComponentViewModel> Components { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IList<ItemRequestViewModel> Items { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "properties")]
        public IList<RequestPropertyViewModel> Properties { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "websocketCommands")]
        public IList<WebsocketCommandViewModel> WebsocketCommands { get; set; }

    }
}
