// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Nozomi.net.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RequestPropertyViewModel
    {
        /// <summary>
        /// Initializes a new instance of the RequestPropertyViewModel class.
        /// </summary>
        public RequestPropertyViewModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RequestPropertyViewModel class.
        /// </summary>
        public RequestPropertyViewModel(System.Guid? guid = default(System.Guid?), int? type = default(int?), string key = default(string), string value = default(string), string requestGuid = default(string))
        {
            Guid = guid;
            Type = type;
            Key = key;
            Value = value;
            RequestGuid = requestGuid;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "guid")]
        public System.Guid? Guid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public int? Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "key")]
        public string Key { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requestGuid")]
        public string RequestGuid { get; set; }

    }
}
