// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Nozomi.net.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SubComputeViewModel
    {
        /// <summary>
        /// Initializes a new instance of the SubComputeViewModel class.
        /// </summary>
        public SubComputeViewModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SubComputeViewModel class.
        /// </summary>
        public SubComputeViewModel(System.Guid? parentComputeGuid = default(System.Guid?), ComputeViewModel parentCompute = default(ComputeViewModel), System.Guid? childComputeGuid = default(System.Guid?), ComputeViewModel childCompute = default(ComputeViewModel), bool? isEnabled = default(bool?))
        {
            ParentComputeGuid = parentComputeGuid;
            ParentCompute = parentCompute;
            ChildComputeGuid = childComputeGuid;
            ChildCompute = childCompute;
            IsEnabled = isEnabled;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "parentComputeGuid")]
        public System.Guid? ParentComputeGuid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "parentCompute")]
        public ComputeViewModel ParentCompute { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "childComputeGuid")]
        public System.Guid? ChildComputeGuid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "childCompute")]
        public ComputeViewModel ChildCompute { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isEnabled")]
        public bool? IsEnabled { get; set; }

    }
}
