// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Nozomi.net.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TypeViewModel
    {
        /// <summary>
        /// Initializes a new instance of the TypeViewModel class.
        /// </summary>
        public TypeViewModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TypeViewModel class.
        /// </summary>
        public TypeViewModel(System.Guid? guid = default(System.Guid?), string slug = default(string), string name = default(string), IList<TypeItemViewModel> items = default(IList<TypeItemViewModel>), IList<RequestViewModel> requests = default(IList<RequestViewModel>))
        {
            Guid = guid;
            Slug = slug;
            Name = name;
            Items = items;
            Requests = requests;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "guid")]
        public System.Guid? Guid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "slug")]
        public string Slug { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IList<TypeItemViewModel> Items { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requests")]
        public IList<RequestViewModel> Requests { get; set; }

    }
}
