// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Nozomi.net.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class UpdateTypeRequestInputModel
    {
        /// <summary>
        /// Initializes a new instance of the UpdateTypeRequestInputModel
        /// class.
        /// </summary>
        public UpdateTypeRequestInputModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UpdateTypeRequestInputModel
        /// class.
        /// </summary>
        public UpdateTypeRequestInputModel(System.Guid? guid = default(System.Guid?), System.Guid? typeGuid = default(System.Guid?), TypeViewModel type = default(TypeViewModel), long? requestId = default(long?), RequestViewModel request = default(RequestViewModel), bool? isDeleted = default(bool?), bool? permanentDeletion = default(bool?), bool? isEnabled = default(bool?))
        {
            Guid = guid;
            TypeGuid = typeGuid;
            Type = type;
            RequestId = requestId;
            Request = request;
            IsDeleted = isDeleted;
            PermanentDeletion = permanentDeletion;
            IsEnabled = isEnabled;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "guid")]
        public System.Guid? Guid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "typeGuid")]
        public System.Guid? TypeGuid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public TypeViewModel Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requestId")]
        public long? RequestId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "request")]
        public RequestViewModel Request { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isDeleted")]
        public bool? IsDeleted { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "permanentDeletion")]
        public bool? PermanentDeletion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isEnabled")]
        public bool? IsEnabled { get; set; }

    }
}
