// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Nozomi.net.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class UpdateWebsocketCommandInputModel
    {
        /// <summary>
        /// Initializes a new instance of the UpdateWebsocketCommandInputModel
        /// class.
        /// </summary>
        public UpdateWebsocketCommandInputModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UpdateWebsocketCommandInputModel
        /// class.
        /// </summary>
        public UpdateWebsocketCommandInputModel(int? type = default(int?), string name = default(string), long? delay = default(long?), System.Guid? requestGuid = default(System.Guid?), bool? isEnabled = default(bool?), long? id = default(long?), System.Guid? guid = default(System.Guid?), IList<UpdateWebsocketCommandPropertyInputModel> properties = default(IList<UpdateWebsocketCommandPropertyInputModel>), bool? isDeleted = default(bool?), bool? permanentDeletion = default(bool?))
        {
            Type = type;
            Name = name;
            Delay = delay;
            RequestGuid = requestGuid;
            IsEnabled = isEnabled;
            Id = id;
            Guid = guid;
            Properties = properties;
            IsDeleted = isDeleted;
            PermanentDeletion = permanentDeletion;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public int? Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "delay")]
        public long? Delay { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requestGuid")]
        public System.Guid? RequestGuid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isEnabled")]
        public bool? IsEnabled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "guid")]
        public System.Guid? Guid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "properties")]
        public IList<UpdateWebsocketCommandPropertyInputModel> Properties { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isDeleted")]
        public bool? IsDeleted { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "permanentDeletion")]
        public bool? PermanentDeletion { get; set; }

    }
}
