// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Nozomi.net.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class UpdateWebsocketCommandPropertyInputModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// UpdateWebsocketCommandPropertyInputModel class.
        /// </summary>
        public UpdateWebsocketCommandPropertyInputModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// UpdateWebsocketCommandPropertyInputModel class.
        /// </summary>
        public UpdateWebsocketCommandPropertyInputModel(long? id = default(long?), System.Guid? guid = default(System.Guid?), int? type = default(int?), string key = default(string), string value = default(string), bool? isEnabled = default(bool?), string commandGuid = default(string), long? commandId = default(long?))
        {
            Id = id;
            Guid = guid;
            Type = type;
            Key = key;
            Value = value;
            IsEnabled = isEnabled;
            CommandGuid = commandGuid;
            CommandId = commandId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "guid")]
        public System.Guid? Guid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public int? Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "key")]
        public string Key { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isEnabled")]
        public bool? IsEnabled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "commandGuid")]
        public string CommandGuid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "commandId")]
        public long? CommandId { get; set; }

    }
}
