// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Nozomi.net.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class UpdateComponentInputModel
    {
        /// <summary>
        /// Initializes a new instance of the UpdateComponentInputModel class.
        /// </summary>
        public UpdateComponentInputModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UpdateComponentInputModel class.
        /// </summary>
        public UpdateComponentInputModel(System.Guid? guid = default(System.Guid?), long? componentTypeId = default(long?), string identifier = default(string), string query = default(string), bool? isDenominated = default(bool?), bool? anomalyIgnorance = default(bool?), bool? storeHistoricals = default(bool?), bool? isDeleted = default(bool?), bool? permanentDeletion = default(bool?), string requestGuid = default(string), IList<UpdateComponentHistoricItemInputModel> history = default(IList<UpdateComponentHistoricItemInputModel>))
        {
            Guid = guid;
            ComponentTypeId = componentTypeId;
            Identifier = identifier;
            Query = query;
            IsDenominated = isDenominated;
            AnomalyIgnorance = anomalyIgnorance;
            StoreHistoricals = storeHistoricals;
            IsDeleted = isDeleted;
            PermanentDeletion = permanentDeletion;
            RequestGuid = requestGuid;
            History = history;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "guid")]
        public System.Guid? Guid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "componentTypeId")]
        public long? ComponentTypeId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "identifier")]
        public string Identifier { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "query")]
        public string Query { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isDenominated")]
        public bool? IsDenominated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "anomalyIgnorance")]
        public bool? AnomalyIgnorance { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "storeHistoricals")]
        public bool? StoreHistoricals { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isDeleted")]
        public bool? IsDeleted { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "permanentDeletion")]
        public bool? PermanentDeletion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requestGuid")]
        public string RequestGuid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "history")]
        public IList<UpdateComponentHistoricItemInputModel> History { get; set; }

    }
}
