// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Nozomi.net.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class UpdateItemInputModel
    {
        /// <summary>
        /// Initializes a new instance of the UpdateItemInputModel class.
        /// </summary>
        public UpdateItemInputModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UpdateItemInputModel class.
        /// </summary>
        public UpdateItemInputModel(System.Guid? guid = default(System.Guid?), bool? isEnabled = default(bool?), string logoPath = default(string), string abbreviation = default(string), string slug = default(string), string name = default(string), int? denominations = default(int?), string denominationName = default(string), IList<UpdateTypeItemInputModel> types = default(IList<UpdateTypeItemInputModel>), IList<UpdateItemPropertyInputModel> properties = default(IList<UpdateItemPropertyInputModel>), IList<UpdateItemSourceInputModel> sources = default(IList<UpdateItemSourceInputModel>), IList<UpdateItemRequestInputModel> requests = default(IList<UpdateItemRequestInputModel>))
        {
            Guid = guid;
            IsEnabled = isEnabled;
            LogoPath = logoPath;
            Abbreviation = abbreviation;
            Slug = slug;
            Name = name;
            Denominations = denominations;
            DenominationName = denominationName;
            Types = types;
            Properties = properties;
            Sources = sources;
            Requests = requests;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "guid")]
        public System.Guid? Guid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isEnabled")]
        public bool? IsEnabled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "logoPath")]
        public string LogoPath { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "abbreviation")]
        public string Abbreviation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "slug")]
        public string Slug { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "denominations")]
        public int? Denominations { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "denominationName")]
        public string DenominationName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "types")]
        public IList<UpdateTypeItemInputModel> Types { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "properties")]
        public IList<UpdateItemPropertyInputModel> Properties { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sources")]
        public IList<UpdateItemSourceInputModel> Sources { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requests")]
        public IList<UpdateItemRequestInputModel> Requests { get; set; }

    }
}
