// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Nozomi.net.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class UpdateItemSourceInputModel
    {
        /// <summary>
        /// Initializes a new instance of the UpdateItemSourceInputModel class.
        /// </summary>
        public UpdateItemSourceInputModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UpdateItemSourceInputModel class.
        /// </summary>
        public UpdateItemSourceInputModel(long? id = default(long?), System.Guid? itemGuid = default(System.Guid?), ItemViewModel item = default(ItemViewModel), long? sourceId = default(long?), SourceViewModel source = default(SourceViewModel), bool? isEnabled = default(bool?), bool? isDeleted = default(bool?), bool? permanentDeletion = default(bool?))
        {
            Id = id;
            ItemGuid = itemGuid;
            Item = item;
            SourceId = sourceId;
            Source = source;
            IsEnabled = isEnabled;
            IsDeleted = isDeleted;
            PermanentDeletion = permanentDeletion;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "itemGuid")]
        public System.Guid? ItemGuid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "item")]
        public ItemViewModel Item { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sourceId")]
        public long? SourceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "source")]
        public SourceViewModel Source { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isEnabled")]
        public bool? IsEnabled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isDeleted")]
        public bool? IsDeleted { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "permanentDeletion")]
        public bool? PermanentDeletion { get; set; }

    }
}
