// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using Newtonsoft.Json;

namespace Nozomi.net.Interfaces
{
    /// <summary>
    /// </summary>
    public partial interface INozomiAPI : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }


        /// <summary>
        /// Gets the IComponent.
        /// </summary>
        IComponentService ComponentService { get; }

        /// <summary>
        /// Gets the IComponentHistoricItemService.
        /// </summary>
        IComponentHistoricItemService ComponentHistoricItemService { get; }

        /// <summary>
        /// Gets the IComponentTypeService.
        /// </summary>
        IComponentTypeService ComponentTypeService { get; }

        /// <summary>
        /// Gets the IComputeService.
        /// </summary>
        IComputeService ComputeService { get; }

        /// <summary>
        /// Gets the IComputeExpressionService.
        /// </summary>
        IComputeExpressionService ComputeExpressionService { get; }

        /// <summary>
        /// Gets the IComputeValueService.
        /// </summary>
        IComputeValueService ComputeValueService { get; }

        /// <summary>
        /// Gets the IConnectService.
        /// </summary>
        IConnectService ConnectService { get; }

        /// <summary>
        /// Gets the IItemService.
        /// </summary>
        IItemService ItemService { get; }

        /// <summary>
        /// Gets the IRequestService.
        /// </summary>
        IRequestService RequestService { get; }

        /// <summary>
        /// Gets the IRequestPropertyService.
        /// </summary>
        IRequestPropertyService RequestPropertyService { get; }

        /// <summary>
        /// Gets the ISubComputeService.
        /// </summary>
        ISubComputeService SubComputeService { get; }

        /// <summary>
        /// Gets the IWebsocketCommandService.
        /// </summary>
        IWebsocketCommandService WebsocketCommandService { get; }

        /// <summary>
        /// Gets the IWebsocketCommandPropertyService.
        /// </summary>
        IWebsocketCommandPropertyService WebsocketCommandPropertyService { get; }

    }
}
